name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: mpas/cineast
      #    tags: latest
      #    tag_with_ref: true
      - name: get jars
        run: |
          docker pull mpas/cineast:latest
          docker create --name cineast mpas/cineast
          docker cp cineast:/opt/cineast/cineast-cli.jar .
          docker container prune -f
      #- name: Upload jar
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: cineast-cli
      #    path: cineast-cli.jar
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'cineast-*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
