name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: print credentials
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          #tags: cineast/app:latest
          tags: mpas/cineast:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
